# This is a basic workflow to help you get started with Actions

name: Bootcamp 2020 Class


on:
  
  push:
    branches: [ master ]
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2

      
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with :
          node-version: 12 

      - name: Install Surge
        run: npm install -g surge
        
        
      - name: Run Surge
        run: surge ./ bootcamp_2020-class_assignment.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
      

